### ISSUE TITLE
Latest commit missing from latest release

### ISSUE THREAD

**Issue by klajo** [ibaton/OpenHAB-binding-SMHI#4]
Hi,

I saw that air pressure was always represented as 0 and discovered that commit  3d280d6 (the change of air pressure from msi to msl) isn't in the 1.6.0 release linked in the README.

Perhaps [create a new release](https://help.github.com/articles/creating-releases/) with that change?

Cheers,
Klas

**Comment by ibaton** [comment]
Hi Klas. I haven't done anything to this app in a long time and have some problems getting the bundle to work with my version of Openhab. 
Would you mind trying out https://drive.google.com/file/d/0B2sLEbuzoWR4djBWSF9USEZHZWs/view?usp=sharing

**Comment by klajo** [comment]
That works fine.

Thanks.

**Comment by ibaton** [comment]
Great to hear that
